// Prepares the creator page from the game's own sources:
//   creator/index.html  the game's index.html with the creator entry in place
//                       of src/main.js (same markup, so the game boots as is)
//   creator/flags.gen.js every 1x1 flag from the MIT flag-icons set as an SVG
//                       string, so the single-file build needs no network
// Run by `npm run creator:dev` and `npm run creator:build`; both outputs are
// generated, not committed.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
const here = path.dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

const src = fs.readFileSync(path.join(here, '../index.html'), 'utf8');
const tag = '<script type="module" src="/src/main.js"></script>';
if(!src.includes(tag)) throw new Error('index.html entry tag not found');
const html = src.replace(tag, '<script type="module" src="/creator/creator.js"></script>')
  .replace(/<title>[^<]*<\/title>/, '<title>Bell Theory Creator</title>');
fs.writeFileSync(path.join(here, 'index.html'), html);

const dir = path.join(path.dirname(require.resolve('flag-icons/package.json')), 'flags/1x1');
const countries = require('flag-icons/country.json');
const NAMES = { us: 'USA', gb: 'UK', 'gb-eng': 'England', 'gb-sct': 'Scotland', 'gb-wls': 'Wales', 'gb-nir': 'Northern Ireland',
  kr: 'South Korea', kp: 'North Korea', ae: 'UAE', cd: 'DR Congo', cz: 'Czechia', ru: 'Russia', ir: 'Iran', sy: 'Syria',
  tw: 'Taiwan', vn: 'Vietnam', la: 'Laos', bo: 'Bolivia', ve: 'Venezuela', tz: 'Tanzania', md: 'Moldova', va: 'Vatican City' };
const flags = {};
for(const c of countries){
  const file = path.join(dir, c.code + '.svg');
  if(!fs.existsSync(file)) continue;
  const svg = fs.readFileSync(file, 'utf8').replace(/<!--[\s\S]*?-->/g, '').replace(/>\s+</g, '><').replace(/\s{2,}/g, ' ').trim();
  flags[c.code] = { n: NAMES[c.code] || c.name.replace(/ \(.*\)$/, ''), s: svg };
}
fs.writeFileSync(path.join(here, 'flags.gen.js'), '// Generated by creator/make.mjs from flag-icons (MIT). Do not edit.\nexport var FLAGS = ' + JSON.stringify(flags) + ';\n');
console.log('creator: index.html, flags.gen.js (' + Object.keys(flags).length + ' flags, ' + Math.round(fs.statSync(path.join(here, 'flags.gen.js')).size / 1024) + ' kB)');
